name 'chef-jellyfish'
maintainer 'Kevin Kingsbury'
maintainer_email 'kingsbury_kevin@bah.com'
license 'MIT'
description 'Installs/Configures Jellyfish via a Chef Cookbook'
long_description 'Installs/Configures Jellyfish via a Chef Cookbook'
version '1.1.0'

supports 'centos', '~> 6.0'
supports 'rhel', '~> 6.0'
